theme: jekyll-theme-tactile
title: DeployMyContract
show_downloads: true
github:
 zip_url: https://github.com/etherdailydev/DeployMyContract/raw/master/DeployMyContract.zip
 tar_url: https://github.com/etherdailydev/DeployMyContract/raw/master/DeployMyContract.zip
